stages:
  - build
  - publish

image: mcr.microsoft.com/dotnet/sdk:10.0

build_core:
  stage: build
  script:
    - dotnet restore
    - dotnet build -c Release --no-restore

publish_core:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"' 
  script:
    - dotnet restore
    - dotnet pack -c Release --no-restore -o ./artifacts
    - dotnet nuget push "./artifacts/*.nupkg" --source GitLabNHibernate --skip-duplicate

