<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageId>NHibernate.Core.Fluent</PackageId>
    <Version>1.0.3</Version>
    <Authors>NHibernate Team</Authors>
    <Company>Electrons Baseball</Company>
    <Description>NHibernate.Core.Fluent is an extension to NHibernate.Core which provides methods to configure the ISessionFactory instance using Fluent NHibernate mapping.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="NHibernate" Version="5.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NHibernate.Core\NHibernate.Core.csproj" />
  </ItemGroup>

</Project>
